services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movement-container
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - PORT=3006
    restart: unless-stopped
